# -*- coding: utf-8 -*-
"""GPS_and_localization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Cmc7oXIDOWoNkoT_REm01sf2-vdAa2k

Question no 4 a
"""

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/content/gps_points.csv")

plt.scatter(df['longitude'],df['latitude'])
plt.show()

map = plt.imread("/content/map.png")

fig, ax = plt.subplots(figsize = (8,7))
ax.scatter(df.longitude, df.latitude, zorder=1, alpha= 0.2, c='b', s=10)
ax.set_title('Plotting hdmap.bag file data on WMU parkview map')
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")
ax.set_xlim(-85.64588,-85.63619)
ax.set_ylim(42.25339,42.25952)
ax.imshow(map, zorder=0, extent = (-85.64588,-85.63619,42.25339,42.25952), aspect= 'equal')